export const ACTION_SAVE_LINTED_RULES = 'SAVE_LINTED_RULES';
export const ACTION_SHOW_LOADING = 'SHOW_LOADING';
export const ACTION_SHOW_ERROR = 'SHOW_ERROR';
export const ACTION_INSPECT_ELEMENT = 'INSPECT_ELEMENT';
